---
locale: en
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_matches
  regexp: won(\W*True\W*,\W*31\W*)
name: Let's play T.E.G.!
